language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.2'
      env: deps='low'

install:
  - if [[ ! $deps ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
  - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
  - vendor/bin/phpspec run --format=dot
  - vendor/bin/phpstan analyse
