language: php

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry composer update --prefer-dist --no-progress --no-suggest --ansi $DEPENDENCIES

jobs:
  include:
    - stage: Test
      php: 7.1
      env: DEPENDENCIES=""
      script: vendor/bin/phpspec run --format=dot

    - stage: Test
      php: 7.1
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpspec run --format=dot

    - stage: Test
      php: 7.2
      env: DEPENDENCIES=""
      script: vendor/bin/phpspec run --format=dot

    - stage: Test
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpspec run --format=dot

    - stage: Test
      php: 7.3
      env: DEPENDENCIES=""
      script: vendor/bin/phpspec run --format=dot

    - stage: Test
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpspec run --format=dot

    - stage: Check Coding Standard
      php: 7.3
      env: DEPENDENCIES=""
      script:
        - composer normalize --dry-run
        - vendor/bin/phpcs

    - stage: Static Analysis
      php: 7.1
      env: DEPENDENCIES=""
      script: vendor/bin/phpstan analyse
